Katalog/Controllers/TalepController.cs
using Katalog.Business.Abstracts;
using Katalog.Dataaccess.Abstracts;
using Katalog.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Katalog.Controllers
{
	public class TalepController : Controller
	{
		private readonly IUrunDal _urunDal;
        private readonly IFirmaService _firmaService;
        private readonly IMarkaService _markaService;
        private readonly ITipService _tipService;
        private readonly IModelService _modelService;
        private readonly IOEMService _oemService;
        private readonly IReferansService _referansService;
        private readonly IUyumlulukService _uyumlulukService;
        private readonly IFileService _fileService;

        public TalepController(IUrunDal urunDal, IFirmaService firmaService, IMarkaService markaService, ITipService tipService, IModelService modelService, IOEMService oemService, IReferansService referansService, IUyumlulukService uyumlulukService, IFileService fileService)
		{
			_urunDal = urunDal;
            _firmaService = firmaService;
            _markaService = markaService;
            _tipService = tipService;
            _modelService = modelService;
            _oemService = oemService;
            _referansService = referansService;
            _uyumlulukService = uyumlulukService;
            _fileService = fileService;
        }
		public IActionResult Index()
        {
            var vm = new UrunViewModel()
            {
                Markalar = _markaService.MarkaList().Data,
                Tipler = _tipService.TipList().Data,
                Modeller = _modelService.ModelList().Data
            };
            return View(vm);
		}
	}
}

Katalog/Views/Shared/Components/Toolbar/_Toolbar.cshtml
@using Katalog.Entity;

@model Kullanici


<!--begin::Toolbar wrapper-->
<div class="d-flex flex-shrink-0">
	
	@if(!User.Identity.IsAuthenticated)
	{
		<div class="d-flex ms-3 me-3">
			<a asp-controller="Auth" asp-action="Login" class="btn btn-flex flex-center bg-body btn-color-gray-700 btn-active-color-primary w-40px w-md-auto h-40px px-0 px-md-6">
				<!--begin::Svg Icon | path: icons/duotune/arrows/arr075.svg-->
				<span class="svg-icon svg-icon-2 svg-icon-primary me-0 me-md-2">
					<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
						<rect opacity="0.5" x="11.364" y="20.364" width="16" height="2" rx="1"
							transform="rotate(-90 11.364 20.364)" fill="currentColor" />
						<rect x="4.36396" y="11.364" width="16" height="2" rx="1" fill="currentColor" />
					</svg>
				</span>
				<!--end::Svg Icon-->
				<span class="d-none d-md-inline">Giriş Yap</span>
			</a>
		</div>
	}

	<!--begin::Create app-->
	<div class="d-flex">
		<a asp-controller="Talep" asp-action="Index"
			class="btn btn-flex flex-center bg-body btn-color-gray-700 btn-active-color-primary w-40px w-md-auto h-40px px-0 px-md-6">
			<!--begin::Svg Icon | path: icons/duotune/general/gen005.svg-->
			<span class="svg-icon svg-icon-2 svg-icon-primary me-0 me-md-2">
				<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path opacity="0.3"
						d="M19 22H5C4.4 22 4 21.6 4 21V3C4 2.4 4.4 2 5 2H14L20 8V21C20 21.6 19.6 22 19 22ZM12.5 18C12.5 17.4 12.6 17.5 12 17.5H8.5C7.9 17.5 8 17.4 8 18C8 18.6 7.9 18.5 8.5 18.5L12 18C12.6 18 12.5 18.6 12.5 18ZM16.5 13C16.5 12.4 16.6 12.5 16 12.5H8.5C7.9 12.5 8 12.4 8 13C8 13.6 7.9 13.5 8.5 13.5H15.5C16.1 13.5 16.5 13.6 16.5 13ZM12.5 8C12.5 7.4 12.6 7.5 12 7.5H8C7.4 7.5 7.5 7.4 7.5 8C7.5 8.6 7.4 8.5 8 8.5H12C12.6 8.5 12.5 8.6 12.5 8Z"
						fill="currentColor" />
					<rect x="7" y="17" width="6" height="2" rx="1" fill="currentColor" />
					<rect x="7" y="12" width="10" height="2" rx="1" fill="currentColor" />
					<rect x="7" y="7" width="6" height="2" rx="1" fill="currentColor" />
					<path d="M15 8H20L14 2V7C14 7.6 14.4 8 15 8Z" fill="currentColor" />
				</svg>
			</span>
			<!--end::Svg Icon-->
			<span class="d-none d-md-inline">Ürün Talep Et</span>
		</a>
	</div>
	<!--end::Create app-->
		

	@if(User.Identity.IsAuthenticated)
	{
		@* <!--begin::Account-->
			<a asp-controller="Account" asp-action="Index">
				<div class="app-navbar-item ms-1 ms-lg-3">
					<!--begin::Menu- wrapper-->
					<div class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-35px h-35px w-md-40px h-md-40px"
						data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-attach="parent"
						data-kt-menu-placement="bottom-end">
						<!--begin::Svg Icon | path: /var/www/preview.keenthemes.com/kt-products/docs/metronic/html/releases/2023-03-24-172858/core/html/src/media/icons/duotune/communication/com006.svg-->
							<span class="svg-icon svg-icon-muted svg-icon-2x"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path opacity="0.3" d="M16.5 9C16.5 13.125 13.125 16.5 9 16.5C4.875 16.5 1.5 13.125 1.5 9C1.5 4.875 4.875 1.5 9 1.5C13.125 1.5 16.5 4.875 16.5 9Z" fill="currentColor"/>
							<path d="M9 16.5C10.95 16.5 12.75 15.75 14.025 14.55C13.425 12.675 11.4 11.25 9 11.25C6.6 11.25 4.57499 12.675 3.97499 14.55C5.24999 15.75 7.05 16.5 9 16.5Z" fill="currentColor"/>
							<rect x="7" y="6" width="4" height="4" rx="2" fill="currentColor"/>
							</svg>
							</span>
						<!--end::Svg Icon-->
					</div>
					<!--end::Menu wrapper-->
				</div>
			</a> *@

			 <a class="ms-5" asp-controller="Account" asp-action="Index" id="profil">
				<div class="app-navbar-item "></div>
					<span class="menu-icon">
						<!--begin::Svg Icon | path: icons/duotune/art/art002.svg-->
						<img width="40" height="40" style="object-fit:cover;border-radius:5px;"
							src='~/app/images/avatars/@(String.IsNullOrEmpty(Model.ImagePath) ? "blank.jpg" : Model.ImagePath)' alt="" />
						<!--end::Svg Icon-->
					</span>
				</a> 
		<!--end::Account-->

		<!--begin::Log Out-->
			<form id="Logout" asp-controller="Auth" asp-action="Logout" method="POST">
				<a id="LogoutButton">
					<div class="app-navbar-item ms-1 ms-lg-3">
						<!--begin::Menu- wrapper-->
						<div class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-35px h-35px w-md-40px h-md-40px"
							data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-attach="parent"
							data-kt-menu-placement="bottom-end">
							<!--begin::Svg Icon | path: /var/www/preview.keenthemes.com/kt-products/docs/metronic/html/releases/2023-03-24-172858/core/html/src/media/icons/duotune/arrows/arr076.svg-->
								<span class="svg-icon svg-icon-muted svg-icon-2hx"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
									<rect opacity="0.3" width="12" height="2" rx="1" transform="matrix(-1 0 0 1 15.5 11)" fill="currentColor"/>
									<path d="M13.6313 11.6927L11.8756 10.2297C11.4054 9.83785 11.3732 9.12683 11.806 8.69401C12.1957 8.3043 12.8216 8.28591 13.2336 8.65206L16.1592 11.2526C16.6067 11.6504 16.6067 12.3496 16.1592 12.7474L13.2336 15.3479C12.8216 15.7141 12.1957 15.6957 11.806 15.306C11.3732 14.8732 11.4054 14.1621 11.8756 13.7703L13.6313 12.3073C13.8232 12.1474 13.8232 11.8526 13.6313 11.6927Z" fill="currentColor"/>
									<path d="M8 5V6C8 6.55228 8.44772 7 9 7C9.55228 7 10 6.55228 10 6C10 5.44772 10.4477 5 11 5H18C18.5523 5 19 5.44772 19 6V18C19 18.5523 18.5523 19 18 19H11C10.4477 19 10 18.5523 10 18C10 17.4477 9.55228 17 9 17C8.44772 17 8 17.4477 8 18V19C8 20.1046 8.89543 21 10 21H19C20.1046 21 21 20.1046 21 19V5C21 3.89543 20.1046 3 19 3H10C8.89543 3 8 3.89543 8 5Z" fill="currentColor"/>
									</svg>
								</span>
							<!--end::Svg Icon-->
						</div>
						<!--end::Menu wrapper-->
					</div>
				</a>
			</form>
		<!--end::Log Out-->
	}
	
</div>
<!--end::Toolbar wrapper-->



<script>
	let host = window.location.pathname;
	let hosts = host.split("/");


	$('#breadcrumb1').html(hosts[1]);
	$('#breadcrumb2').html(hosts[2]);

	console.log(hosts);
	
	const button = document.getElementById('LogoutButton');

		button.addEventListener('click', e =>{
			e.preventDefault();

			Swal.fire({
				title: "Çıkış Yapmak Üzeresiniz!",
				html: `Çıkış yaparsanız tekrar giriş yapmanız gerekir.`,
				icon: "warning",
				buttonsStyling: false,
				showCancelButton: true,
				confirmButtonText: "Çıkış Yap",
				cancelButtonText: 'Vazgeç',
				reverseButtons: true,
				customClass: {
					confirmButton: "btn btn-danger",
					cancelButton: 'btn btn-primary'
				}
			}).then((result) =>{
				console.log(result);
				if(result.isConfirmed)
				{
					$('#Logout').submit();
				}
			});
		});
</script>